from unittest import TestCase


class TestSolution(TestCase):
    def test_fourSum_3(self):
        self.fail()
